# For more information: https://laravel.com/docs/sail
version: '3'
services:
    webconf.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - webconf
        depends_on:
            - webconf_mysql
    webconf_mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'webconf-mysql:/var/lib/mysql'
        networks:
            - webconf
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    webconf_redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'webconf-redis:/data'
        networks:
            - webconf
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
    webconf_laravel-echo-server:
        image: oanhnn/laravel-echo-server:latest
        depends_on:
            - webconf_redis
            - webconf.test
        environment:
            LARAVEL_ECHO_SERVER_AUTH_HOST: '${LARAVEL_ECHO_SERVER_AUTH_HOST}'
            LARAVEL_ECHO_SERVER_DEBUG: 'true'
            LARAVEL_ECHO_SERVER_DB: redis
            REDIS_HOST: webconf_redis
            REDIS_PORT: '${FORWARD_REDIS_PORT:-6379}:6379'
            REDIS_PREFIX: '${REDIS_PREFIX}'
            REDIS_DB: 0
        networks:
            - webconf
        ports:
            - '${LARAVEL_ECHO_SERVER_PORT:-6001}:6001'
        restart: unless-stopped
        healthcheck:
            test: node /usr/local/src/healthcheck.js
            interval: 3s
            timeout: 3s
            retries: 10
networks:
    webconf:
        driver: bridge
volumes:
    webconf-mysql:
        driver: local
    webconf-redis:
        driver: local
